package org.mule.transport.sftp;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.apache.log4j.Logger;
/**
 * 
 * @author Indira Mallick
 *
 */
public class StorePolledFiles {
	
	Connection conn = null;	
	Statement stmt = null;
	PreparedStatement preparedStatement = null;
	final Logger logger = Logger.getRootLogger();
	/**
	 * 
	 * @throws Exception
	 */
	public void initDB() throws Exception
	{
		String dbURL = "jdbc:derby:memory:muleEmbeddedDB;create=true";
		Class.forName("org.apache.derby.jdbc.EmbeddedDriver").newInstance();
		conn = DriverManager.getConnection(dbURL);
		conn.setAutoCommit(false);
		DatabaseMetaData dbmd = conn.getMetaData();
		stmt = conn.createStatement();
		ResultSet rs = dbmd.getTables(null, "APP", "FILEDB", null);
		if (!rs.next() ) {
			stmt.executeUpdate("CREATE TABLE FILEDB(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0)  NOT NULL PRIMARY KEY,FILENAME VARCHAR(255))");
			logger.info("Table is Created to store the polled file ");
		} else{
			//logger.info("Skipped the table creation script as table is already created");
		}
		stmt.close();
		rs.close();
	}
	/**
	 * 
	 * @param FName
	 * @param FPath
	 * @throws Exception
	 */
	public void insertPolledFileToDB( String FName ) throws Exception
	{
		String insertFiletoDB = "INSERT INTO FILEDB"
				+ "(FILENAME) VALUES"
				+ "(?)";
		preparedStatement = conn.prepareStatement(insertFiletoDB);
		preparedStatement.setString(1, FName);
		preparedStatement.executeUpdate();
		conn.commit();
		preparedStatement.close();
		
	}
	/**
	 * 
	 * @param FName
	 * @return
	 * @throws Exception
	 * 
	 * 
	 */	
	public boolean isFileAlreadyProcessed(String FName) throws Exception
	{
		boolean isFileAlreadyProcessed = false;
		//logger.info("Received file " + FName + " is processed:::" + isFileAlreadyProcessed);
		String selectFile = "SELECT FILENAME FROM FileDB where FILENAME = " + "(?)";
		preparedStatement = conn.prepareStatement( selectFile );
		preparedStatement.setString(1, FName);
		ResultSet rs = preparedStatement.executeQuery();
		while( rs.next() ) {
			isFileAlreadyProcessed = true;
		}
		return isFileAlreadyProcessed;
		
	}
}
